on: #[push, pull_request, workflow_dispatch]
  push: # only auto build on a mush to main
    branches: [ "main" ]
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
